# Generated by Django 3.1.1 on 2020-09-25 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200924_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 12, 27, 17, 276396, tzinfo=utc)),
        ),
    ]
