# Generated by Django 3.1.1 on 2020-09-25 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200925_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_by',
            field=models.TextField(default=datetime.datetime(2020, 9, 25, 12, 33, 24, 787036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 12, 33, 24, 786890, tzinfo=utc)),
        ),
    ]
